### ISSUE TITLE
Line Number symbol missing on gVim 7.3 (windows)

### ISSUE THREAD

**Issue by summivox** [nicolalamacchia/powerline-consolas#1]
Your font:
![ScreenClip 2 ](https://f.cloud.github.com/assets/1770521/144884/31f599aa-7441-11e2-8b66-12dd5243d6ca.png)

http://codejury.com/consolas-font-in-vim-powerline-windows/ :
![ScreenClip 3 ](https://f.cloud.github.com/assets/1770521/144886/322cb3c2-7441-11e2-9ec4-0b5a12cef4c9.png)

Why? Otherwise working for `vim-powerline`.

**Comment by nicolalamacchia** [comment]
Sorry for the delay, can you provide more information on your Win version, how did you install the font and Powerline and so on? Are you using a recent snapshot of Powerline?
This is strange, it works well for me on two different Win7 installations and linux. Here's what I see:

![powerline-consolas](https://f.cloud.github.com/assets/2530868/236396/bff7307e-87e7-11e2-927b-214274631a8c.png)

**Comment by summivox** [comment]
Never mind--it's the older `vim-powerline`, written in `.vim` (no python). I switched back to it because the newer python-powered one isn't that stable on my machine. I'll probably try it when the project more or less settles down ;)

**Comment by wangqinhu** [comment]
I have a similar problem on macOS Sierra 10.12.1, vim 7.4
I remember it worked for about 1-2 hours, suddenly the line number displayed incorrectly.
Maybe caused by conflict between systems consolas font? I disabled the system one during this time. But re-enable it does not work. I don't know, please give me some suggestions. I really like this font and used for more than one year in my old Mac, hope I can continue to use this one without changing to others.
Besides, other powerline fonts work well.

Thanks.

![ln](https://cloud.githubusercontent.com/assets/5449932/20039573/4e1d9b90-a481-11e6-8c94-75554c38019c.png)
