### ISSUE TITLE
tmux segments broken

### ISSUE THREAD

**Issue by sabl0r** [nicolalamacchia/powerline-consolas#2]
Hey,

thank you for patching Consolas. The special glyphs work perfect for me.

I also use powerline for tmux which uses some other utf-8 characters.
These characters work with Consolas set as font in Word and Firefox.
Just look at the source at https://github.com/Lokaltog/powerline/blob/develop/powerline/segments/common.py#L444

The arrows look just fine in Firefox.

![tmux](https://f.cloud.github.com/assets/1169879/237437/de0995d0-8813-11e2-84bd-a3ced3a8ac7a.png)

Do you have any idea what could be the problem? Is it PuTTY? The font itself seems to support those characters.

Edit: seems to be a PuTTY issue: http://superuser.com/a/393877

**Comment by nicolalamacchia** [comment]
Hi, did you try also with other fonts? I can't see that glyphs with Consolas (patched or unpatched). Maybe Word and Firefox use a [fallback font](http://en.wikipedia.org/wiki/Fallback_font) for the missing glyphs. I can try to add them, but actually I think that you should open an issue for Powerline, since it should use glyphs compatible at least with all the most popular programming fonts.
For now patch the script manually: open the source file with Vim and replace the first symbol with (in insert mode) `CTRL-k -!` and the second one with `CTRL-k -v` (`CTRL-k` is the default command to insert digraphs) to obtain: ↑ and ↓ respectively (see `:he digraphs` in Vim).
In PuTTY you just need to set the UTF-8 encoding:
- open PuTTY configuration;
- go to Window > Translation;
- in the box _Remote character set_ choose `UTF-8`.

Note that you must have the font installed _locally_!
Thanks for the feedback ;)

**Comment by sabl0r** [comment]
Thanks for your detailed answer :)
You're right, Consolas does not include that characters. For fun, I tried to copy the arrow characters from DejaVuSans (DejaVuSansMono doesn't include them neither...) to your patched font with fontforge. But that didn't work as expected. It messed up the whole font ;)
Which tool did you use to patch Consolas?

But you're probably right, maybe I should mention it in an issue over at powerline.

**Comment by nicolalamacchia** [comment]
> But that didn't work as expected. It messed up the whole font ;)

This is due to the fact that you lose the [OpenType](http://en.wikipedia.org/wiki/OpenType) information during the font generation process with FontForge.
I'm not a font guru and the first impact with FF has left me a little muddled, so I used [FontLab](http://en.wikipedia.org/wiki/FontLab) (proprietary) that I found rather straightforward compared to FF, especially when it comes to the OpenType features. (Although [Wikipedia states](http://en.wikipedia.org/wiki/FontForge#Features) that the two are pretty equivalent in terms of features, so there should be a way - that I ignore - to tinker with the OpenType features in FF too.)

**Comment by sabl0r** [comment]
Thank you for your support. I now just appended both arrow characters to Consolas with FontLab. The other symbols used by the default tmux theme are stupid. I will just remove them ;)
