### ISSUE TITLE
Bold glyphs

### ISSUE THREAD

**Issue by petobens** [nicolalamacchia/powerline-consolas#3]
I'm having this [problem](https://github.com/bling/vim-airline/issues/207) with airline plugin which uses powerline (not vim-powerline) fonts. Are the bold glyphs patched properly? Bold fancy glyphs are not rendered properly.

**Comment by nicolalamacchia** [comment]
I did not patch the bold, italic and bold italic styles, see [this](https://github.com/nicolalamacchia/powerline-consolas/blob/master/README.md#why-overwrite). You can try to set a fallback, but I recommend you to avoid using bold, italic or both if you can.

Anyway, I do use Airline with no problems on Linux. I had a simlilar issue with some symbols, but it wasn't
related to the patched Consolas, since I was using Inconsolata with [this method](https://powerline.readthedocs.org/en/latest/installation/linux.html#fontconfig)! I fixed that easily.

You should consider this font to work only with the official Powerline.
